version: "3"

services:
    influxdb:
        image: influxdb:2.4
        container_name: influxdb
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_DB=defaultdb
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
            - INFLUXDB_HTTP_AUTH_ENABLED=true
        volumes:
            - influxdb-data:/var/lib/influxdb2

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
        volumes:
            - grafana-data:/var/lib/grafana
        depends_on:
            - influxdb

volumes:
    influxdb-data:
    grafana-data:
